### ISSUE TITLE
Feedback Técnico

### ISSUE THREAD

**Issue by RuthSalvador** [vbiaggi10/lim-2018-05-bc-core-pm-socialnetwork#39]
# Recomendaciones de mejora 

### Estructura de carpetas:
Están por buen camino, te sugiero que tengas una carpeta donde estén todas las vistas de html a excepción del `index.html`, también subcarpetas dentro de js; en el caso de imágenes, puedes tenerlas todas en una carpeta o subirlas en la nube y luego linkearlas.

### package.json:
Hay `scripts` que no estás utilizando, es mejor retirarlos; en el caso de usar jest para los test, puedes colocar coverage para ver la cobertura que tienes `"tests": "jest --coverage"`
https://github.com/vbiaggi10/lim-2018-05-bc-core-pm-socialnetwork/blob/1aa4bfe72facf9c1765fd9667a14a3bc96e74e29/package.json#L6-L14
además si no vas a usar mocha o chai, es mejor eliminar esas dependencias.

### Git:
Es recomendable que "comitées" por funcionalidades y no en bloque, a la vez estos commits deben ser descriptivos (eviten usar descripciones como ok, ya está, etc). Recuerda verificar el nombre de los `pull requests` ya que éstos se ven reflejados como commits, por lo que deben ser descriptivos o asociados a un issue.

### Github:
Es necesario que tu siguiente proyecto tenga como mínimo los niveles solicitados. Este tema puedes preguntarlo en los Q&A.

### Javascript:
- Hay variables declaradas que no se usan como: `dataBase`, `writingPost`, `uploadingImage`
- Se considera una buena práctica utilizar los operadores de igualdad de tipo seguro `===` y `!==` en lugar de sus contrapartes regulares `==` y `!=`.
- Recuerda usar `ES6`
- Cada sentencia debe terminar con `;`
- En la función `createPost` de `posts.js`, puedes declarar las variables afuera; también te sugiero usar [plantillas de texto](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/template_strings)
- El backslash (barra invertida `\`) "escapa" los caracteres de comillas simples en una cadena de texto para que sean interpretadas, de tal manera que no generes errores ortográficos en el inglés.
https://github.com/vbiaggi10/lim-2018-05-bc-core-pm-socialnetwork/blob/1aa4bfe72facf9c1765fd9667a14a3bc96e74e29/src/js/signup.js#L17
así: `alert('Your password doesn\'t mach');`

### Tests:
Recuerda llegar a lo mínimo requerido usa `--coverage` para verificar tu cobertura.
![image](https://user-images.githubusercontent.com/25906896/43855510-75f81078-9b0b-11e8-9af8-f406270c6aa5.png)

### index.html:
Recuerda que debes validar tu `html`, te recomendamos revisar el [enlace](https://validator.w3.org/nu/?doc=https%3A%2F%2Fnatalyporras.github.io%2Flim-2018-05-bc-core-pm-socialnetwork%2Fsrc%2Fwall.html) para mayor especificación, también valida los otros `html`que tienes. Te sugerimos utilizar más etiquetas semánticas, así como sus propiedades. Cuida tu indentación. 

### style.css:
Hay archivos `css` de bootstrap, emoji, etc; que puedes agruparlo en una carpeta aparte de tu propio css. 
Están usando varios framework y estilos repetitivos, primero exploten un framework antes de agregar otro innecesariamente: bootstrap3, 4, etc.  No es necesario setear cuando utilizas un framework, ya que puedes alterar los estilos de éste.
https://github.com/vbiaggi10/lim-2018-05-bc-core-pm-socialnetwork/blob/1aa4bfe72facf9c1765fd9667a14a3bc96e74e29/src/css/sign.css#L3-L9

Por último te recomendamos utilizar convenciones para tus archivos, de tal forma que se mantenga un orden y se vea profesional.
Recuerda declarar tus variables, clases, id con nombres en inglés y descriptivas.

Espero puedas implementar este feedback en tus proyectos.

**Comment by vbiaggig** [comment]
Gracias @RuthSalvador  <3
